### PR TITLE
Add some rust queries

### PR DESCRIPTION
**Pull request by schmidma**
This adds some queries for the rust language

### CODE REVIEW

**Comment by mizlan** [comment]
Thank you! This seems ready to merge but could you check the nodes for vector literals and other data structure literals? I think that is a nice feature in addition to the arguments and parameters.

**Comment by sharksforarms** [comment]
Was planning on making a PR but noticed one was open for rust already.

Here's some I've come across so far with TSPlayground, I think it's pretty comprehensive and may be a good start :)

```
[
  (arguments)
  (array_expression)
  (declaration_list)
  (enum_variant_list)
  (field_declaration_list)
  (meta_arguments)
  (parameters)
  (trait_bounds)
  (tuple_expression)
  (type_arguments)
  (type_parameters)
] @iswap-list
```

**Comment by mizlan** [comment]
Thanks! @schmidma can you confirm those other nodes and add them to the Rust query?

**Comment by schmidma** [comment]
I added the nodes suggested by @sharksforarms and also verified the functionality.

**Comment by mizlan** [comment]
Cool! This looks pretty comprehensive, at least for now, so I'm going to merge.

**Comment by schmidma** [comment]
Nice, that was quick, thank you

**Pull request merged**
